/*
 * Copyright 2024 C Thing Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.cthing.gradle.plugins.locc.reports;

import java.io.File;

import org.gradle.api.Task;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.provider.Property;
import org.gradle.api.reporting.Report;

import groovy.lang.Closure;


/**
 * Base class for the reports generated by this plugin.
 */
public abstract class AbstractLoccReport implements LoccReport {

    protected static final String REPORT_BASE_NAME = "locc";

    protected final Task task;

    private final String name;
    private final String displayName;
    private final RegularFileProperty destination;
    private final Property<Boolean> required;

    protected AbstractLoccReport(final Task task, final String name, final String displayName,
                                 final boolean required) {
        this.task = task;
        this.name = name;
        this.displayName = displayName;

        final ObjectFactory objects = task.getProject().getObjects();
        this.destination = objects.fileProperty();
        this.required = objects.property(Boolean.class).convention(required);
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public String getDisplayName() {
        return this.displayName;
    }

    @Override
    public OutputType getOutputType() {
        return OutputType.FILE;
    }


    @Override
    public Property<Boolean> getRequired() {
        return this.required;
    }

    @Override
    public RegularFileProperty getOutputLocation() {
        return this.destination;
    }

    @Override
    @Deprecated
    public void setDestination(final File file) {
        this.destination.set(file);
    }

    @Override
    @SuppressWarnings("rawtypes")
    public Report configure(final Closure closure) {
        this.task.getProject().configure(this, closure);
        return this;
    }
}
