/*
 * Copyright 2024 C Thing Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.cthing.gradle.plugins.locc.reports;

import org.cthing.gradle.plugins.locc.CountsCache;
import org.gradle.api.provider.Property;
import org.gradle.api.reporting.SingleFileReport;
import org.gradle.api.tasks.Input;


/**
 * Represents a line count report generated by the plugin.
 */
public interface LoccReport extends SingleFileReport {

    /**
     * Obtains the flag indicating whether to report file pathnames as relative to the root of the Gradle project.
     * The default is {@code true} to show pathnames relative to the project root.
     *
     * @return Flag indicating whether to report file pathnames as relative to the Gradle project root.
     */
    @Input
    Property<Boolean> getShowRelativePaths();

    /**
     * Writes the line count report in a specific file format.
     *
     * @param countsCache Cache of line count data to report
     */
    void generateReport(CountsCache countsCache);
}
