name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '5'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run clean build javadoc
        run: ./gradlew clean build javadoc
